## Pamndas Test

In [3]:
import pandas as pd

df = pd.read_csv('liverpool.csv')
print(df)

              Name Position  Born  Number Nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil


## Numpy / Numurical Python

In [7]:
import numpy 

array1 = numpy.array([2,3,4,5,6,7,1,1,2,3])
array1

array([2, 3, 4, 5, 6, 7, 1, 1, 2, 3])

In [8]:
type(array1)

numpy.ndarray

In [9]:
array1.shape

(10,)

In [12]:
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [14]:
array2.shape
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
array1.size

10

In [16]:
array2.size

12

In [18]:
array1 = numpy.random.random(6)
print(array1)

[0.36845693 0.44842244 0.89116758 0.07900833 0.82094579 0.04053917]


In [20]:
array1 = numpy.arange(2,7)
print(array1)

[2 3 4 5 6]


In [21]:
array1 = numpy.arange(3,17,3)
print(array1)

[ 3  6  9 12 15]


In [24]:
import numpy as np

array1 = np.full(6,0)
array2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([0, 0, 0, 0, 0, 0])

In [26]:
array2[1]

array([5, 6, 7, 8])

In [27]:
array3 = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
array3[:3]

array([1, 2, 3])

In [30]:
array1 = np.arange(10)
array2 = np.arange(10,20)

print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [35]:
print(array1 * 2 )
print(array1 ** 2 )
print(array1 / 2 )
print(array1 + array2)
array3 = array1 + array2

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[10 12 14 16 18 20 22 24 26 28]


In [36]:
array3 > 4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
array4 = array3 > 4
np.where(array4)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

# Code Eat - Pandas / 220611

In [14]:
import pandas as pd
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 50, 70], ['yoonsoo', 50, 46]]
my_df = pd.DataFrame(two_dimensional_list, columns = ['name', 'english_score', 'math_score'])

In [20]:
import numpy as np
import pandas as pd

names = ['cho', 'jin', 'keyom', 'park']
english_scores = [50, 89, 68, 88]
math_scores = [86, 31, 91, 75]

dic1 = {
    'name' : names,
    'english_score' : english_scores,
    'math_score' : math_scores    
}

df1 = pd.DataFrame(dic1)
df1

name  english_score  math_score
0    cho             50          86
1    jin             89          31
2  keyom             68          91
3   park             88          75

In [28]:
import pandas as pd
iphone_df = pd.read_csv('iphone.csv', index_col = 0)
iphone_df.index
iphone_df.columns
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

# '22.6.12 DataFrame indexing 

In [14]:
import pandas as pd
iphone_df = pd.read_csv('iphone.csv', index_col = 0)
iphone_df.loc['iPhone X']
iphone_df.loc['iPhone X', :]
type(iphone_df.loc['iPhone X', :])

iphone_df.loc[:, '출시일']
iphone_df['출시일']
# iphone_df
# iphone_df.loc['iphone 8', '메모리']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [27]:
iphone_df.loc[iphone_df['디스플레이']>5]
iphone_df['디스플레이']>5
iphone_df['Face ID'] == 'Yes'

iphone_df.loc[iphone_df['Face ID'] == 'Yes']

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [32]:
conditions1= (iphone_df['Face ID'] == 'Yes') & (iphone_df['디스플레이']>5)

In [33]:
iphone_df.loc[(iphone_df['Face ID'] == 'Yes') & (iphone_df['디스플레이']>5)]
iphone_df.loc[conditions1]

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [1]:
iphone_df.iloc[2,4]
iphone_df.iloc[[1,3], [1,4]]
iphone_df.iloc[3:, 1:4]

NameError: name 'iphone_df' is not defined

In [8]:
import pandas as pd
iphone_df = pd.read_csv('iphone.csv', index_col = 0)

In [11]:
iphone_df['디스플레이'] >5
iphone_df.loc[iphone_df['디스플레이'] >5] = 'p'
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus           p     p    p         p       p
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus           p     p    p         p       p
iPhone X                p     p    p         p       p
iPhone XS               p     p    p         p       p
iPhone XS Max           p     p    p         p       p

In [14]:
iphone_df.iloc[[1,3],[1,4]] = 'v'
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No
iPhone 7 Plus           p     v    p         p       v
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No
iPhone 8 Plus           p     v    p         p       v
iPhone X                p     p    p         p       p
iPhone XS               p     p    p         p       p
iPhone XS Max           p     p    p         p       p

In [26]:
import pandas as pd
iphone_df = pd.read_csv('iphone.csv', index_col = 0)

iphone_df['제조사'] = 'Apple' 
iphone_df.loc['iPhone XR'] = ['2018-10-26', 6.1, '3.1GB', 'iOS 12.0.1', 'Yes', 'Apple']
iphone_df

iphone_df.drop('iPhone XR', axis='index', inplace=False)
iphone_df
iphone_df.drop('제조사', axis='columns', inplace=True)
iphone_df

출시일  디스플레이    메모리       출시 버전 Face ID
iPhone 7       2016-09-16    4.7    2GB    iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5    3GB    iOS 10.0      No
iPhone 8       2017-09-22    4.7    2GB    iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5    3GB    iOS 11.0      No
iPhone X       2017-11-03    5.8    3GB    iOS 11.1     Yes
iPhone XS      2018-09-21    5.8    4GB    iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5    4GB    iOS 12.0     Yes
iPhone XR      2018-10-26    6.1  3.1GB  iOS 12.0.1     Yes

In [31]:
import pandas as pd
liverpool_df = pd.read_csv('liverpool.csv', index_col = 0)
liverpool_df.rename(columns={'position': 'Position'}, inplace= True)
liverpool_df

Position  born  number nationality
Roberto Firmino       FW  1991   no. 9      Brazil
Sadio Mane            FW  1992  no. 10     Senegal
Mohamed Salah         FW  1992  no. 11       Egypt
Joe Gomez             DF  1997  no. 12     England
Alisson Becker        GK  1992  no. 13      Brazil

In [37]:
liverpool_df.index.name = 'Player name'
liverpool_df['Player Name'] = liverpool_df.index
liverpool_df.set_index('number', inplace=True)
liverpool_df

Position  born nationality      Player Name
number                                            
no. 9        FW  1991      Brazil  Roberto Firmino
no. 10       FW  1992     Senegal       Sadio Mane
no. 11       FW  1992       Egypt    Mohamed Salah
no. 12       DF  1997     England        Joe Gomez
no. 13       GK  1992      Brazil   Alisson Becker

In [9]:
import pandas as pd
laptops_df = pd.read_csv('laptops.csv', index_col = 0)
laptops_df.tail(3)
laptops_df.shape
laptops_df.info()
laptops_df.describe()
laptops_df.sort_values(by='price', ascending=False, inplace=True)
laptops_df

<class 'pandas.core.frame.DataFrame'>
Index: 167 entries, Dell to Asus
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   model               167 non-null    object 
 1   ram                 167 non-null    int64  
 2   hd_type             167 non-null    object 
 3   hd_size             167 non-null    int64  
 4   screen_size         167 non-null    float64
 5   price               167 non-null    int64  
 6   processor_brand     167 non-null    object 
 7   processor_model     167 non-null    object 
 8   clock_speed         166 non-null    float64
 9   graphic_card_brand  163 non-null    object 
 10  graphic_card_size   81 non-null     float64
 11  os                  167 non-null    object 
 12  weight              160 non-null    float64
 13  comments            55 non-null     object 
dtypes: float64(4), int64(3), object(7)
memory usage: 19.6+ KB


model  ram hd_type  hd_size  screen_size  \
brand                                                                      
Apple          MacBook Pro (TouchBar)   16     ssd      512         15.0   
Alienware                 15 Notebook   16     hdd     1024         15.6   
Alienware          AW13R3-7000SLV-PUS    8     ssd      256         13.3   
Acer                      Predator 17   16     ssd      256         17.3   
Microsoft      Surface Book CR9-00013    8     ssd      128         13.5   
...                               ...  ...     ...      ...          ...   
Acer                  Aspire ES1-523     4     hdd     1024         15.6   
Acer         A315-31-P4CRUN.GNTSI.002    4     hdd      500         15.6   
Acer       Aspire ES-15 NX.GKYSI.010     4     hdd      500         15.6   
Acer          A315-31CDC UN.GNTSI.001    2     ssd      500         15.6   
Acer                  Aspire SW3-016     2     ssd       32         10.1   

            price processor_brand processor_model  clock_speed  \
brand                                                            
Apple      226000           intel              i7         2.70   
Alienware  199000           intel              i7         2.60   
Alienware  190256           intel              i7         3.00   
Acer       178912           intel              i7         2.60   
Microsoft  178799           intel              i5         1.80   
...           ...             ...             ...          ...   
Acer        19465             amd         A4-7210         1.80   
Acer        18990           intel         pentium         1.10   
Acer        17990             amd         A4-7210         1.80   
Acer        17990           intel         Celeron         1.10   
Acer        13872           intel      Atom Z8300         1.44   

          graphic_card_brand  graphic_card_size       os  weight  \
brand                                                              
Apple                  intel                2.0      mac     2.5   
Alienware             nvidia                8.0  windows     3.5   
Alienware             nvidia                6.0  windows     2.6   
Acer                  nvidia                NaN  windows     4.2   
Microsoft              intel                NaN  windows     1.5   
...                      ...                ...      ...     ...   
Acer                     amd                NaN    linux     2.4   
Acer                   intel                NaN  windows     NaN   
Acer                     amd                NaN  windows     2.4   
Acer                   intel                NaN  windows     2.1   
Acer                   intel                NaN  windows     1.2   

                                                    comments  
brand                                                         
Apple                                                    NaN  
Alienware     Maximum Display Resolution : 1920 x 1080 pixel  
Alienware  13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...  
Acer                                     Integrated Graphics  
Microsoft                                                NaN  
...                                                      ...  
Acer                                                     NaN  
Acer                                                     NaN  
Acer                                                     NaN  
Acer                                                     NaN  
Acer                                                     NaN  

[167 rows x 14 columns]

In [16]:
import pandas as pd
laptops_df = pd.read_csv('laptops.csv')
laptops_df
laptops_df['brand']
laptops_df['brand'].unique()
laptops_df['brand'].describe()



count     167
unique      8
top        HP
freq       55
Name: brand, dtype: object

In [29]:
import pandas as pd
world_cities_df = pd.read_csv('world_cities.csv')

world_cities_df['City / Urban area'].value_counts().shape
world_cities_df['Country'].value_counts().shape


(61,)

In [54]:
condition1 = world_cities_df['Population']/world_cities_df['Land area (in sqKm)']
world_cities_df['Density'] = condition1
# world_cities_df.['Density'].describe()

world_cities_df.sort_values(by= 'Density', ascending=False, inplace=True)
world_cities_df

#world_cities_df[condition1, 'City / Urban area']

Unnamed: 0 City / Urban area   Country  Population  Land area (in sqKm)  \
75           75            Mumbai     India    14350000                  484   
74           74           Kolkata     India    12700000                  531   
101         101           Karachi  Pakistan     9800000                  518   
99           99             Lagos   Nigeria    13400000                  738   
34           34          Shenzhen     China     8000000                  466   
..          ...               ...       ...         ...                  ...   
194         195       Chattanooga       USA      344000                  751   
223         224         Asheville       USA      222000                  536   
57           57               Pau    France      181000                  450   
220         221           Hickory       USA      188000                  546   
196         197   Barnstable Town       USA      244000                  741   

          Density  
75   29648.760331  
74   23917.137476  
101  18918.918919  
99   18157.181572  
34   17167.381974  
..            ...  
194    458.055925  
223    414.179104  
57     402.222222  
220    344.322344  
196    329.284750  

[249 rows x 6 columns]

In [75]:
import pandas as pd
world_cities_df = pd.read_csv('world_cities.csv')

Rank_df = world_cities_df['Country'].value_counts()
# Rank_df.head(20)
Rank_df[Rank_df==4]

Italy    4
Name: Country, dtype: int64

# 22.7.23 코드잇 다시 공부

In [5]:
!pip install seaborn == 0.9.0

ERROR: Invalid requirement: '=='


In [2]:
import pandas as pd
import seaborn as sns