## Pamndas Test

In [3]:
import pandas as pd

df = pd.read_csv('liverpool.csv')
print(df)

              Name Position  Born  Number Nationality
0  Roberto Firmino       FW  1991   no. 9      Brazil
1       Sadio Mane       FW  1992  no. 10     Senegal
2    Mohamed Salah       FW  1992  no. 11       Egypt
3        Joe Gomez       DF  1997  no. 12     England
4   Alisson Becker       GK  1992  no. 13      Brazil


## Numpy / Numurical Python

In [7]:
import numpy 

array1 = numpy.array([2,3,4,5,6,7,1,1,2,3])
array1

array([2, 3, 4, 5, 6, 7, 1, 1, 2, 3])

In [8]:
type(array1)

numpy.ndarray

In [9]:
array1.shape

(10,)

In [12]:
array2 = numpy.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [14]:
array2.shape
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
array1.size

10

In [16]:
array2.size

12

In [18]:
array1 = numpy.random.random(6)
print(array1)

[0.36845693 0.44842244 0.89116758 0.07900833 0.82094579 0.04053917]


In [20]:
array1 = numpy.arange(2,7)
print(array1)

[2 3 4 5 6]


In [21]:
array1 = numpy.arange(3,17,3)
print(array1)

[ 3  6  9 12 15]


In [24]:
import numpy as np

array1 = np.full(6,0)
array2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

array([0, 0, 0, 0, 0, 0])

In [26]:
array2[1]

array([5, 6, 7, 8])

In [27]:
array3 = np.array([1,2,3,4,5,6,7,8,9])

In [28]:
array3[:3]

array([1, 2, 3])

In [30]:
array1 = np.arange(10)
array2 = np.arange(10,20)

print(array1)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [35]:
print(array1 * 2 )
print(array1 ** 2 )
print(array1 / 2 )
print(array1 + array2)
array3 = array1 + array2

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[10 12 14 16 18 20 22 24 26 28]


In [36]:
array3 > 4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
array4 = array3 > 4
np.where(array4)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

# Code Eat - Pandas / 220611

In [14]:
import pandas as pd
two_dimensional_list = [['dongwook', 50, 86], ['sineui', 50, 70], ['yoonsoo', 50, 46]]
my_df = pd.DataFrame(two_dimensional_list, columns = ['name', 'english_score', 'math_score'])

In [20]:
import numpy as np
import pandas as pd

names = ['cho', 'jin', 'keyom', 'park']
english_scores = [50, 89, 68, 88]
math_scores = [86, 31, 91, 75]

dic1 = {
    'name' : names,
    'english_score' : english_scores,
    'math_score' : math_scores    
}

df1 = pd.DataFrame(dic1)
df1

name  english_score  math_score
0    cho             50          86
1    jin             89          31
2  keyom             68          91
3   park             88          75

In [28]:
import pandas as pd
iphone_df = pd.read_csv('iphone.csv', index_col = 0)
iphone_df.index
iphone_df.columns
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes